dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/loggingexporter v0.81.0

receivers:
  - gomod:
      github.com/null-ref-ex/otel-receivers/httpdatareceiver 1e75ceebba9aa22825abe338c531a05d33f468fe