// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

module go.opentelemetry.io/collector/cmd/builder

go 1.19

require (
	github.com/null-ref-ex/otel-receivers/httpdatareceiver 1e75ceebba9aa22825abe338c531a05d33f468fe
	go.opentelemetry.io/collector/exporter/loggingexporter v0.81.0
	go.opentelemetry.io/collector v0.81.0
)



// ambiguous import: found package cloud.google.com/go/compute/metadata in multiple modules
replace cloud.google.com/go => cloud.google.com/go v0.110.2
